name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go install github.com/mitchellh/gox@latest
        gox -os="linux darwin" -arch="amd64 arm64" ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          qa-cli_*
